import * as vscode from 'vscode';
import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs/promises';
import { execFile } from 'child_process';
import { TEST_PROMPT } from './prompts';

async function analyzeTestResults(
  generatedCode: string,
  testOutput: string,
  stream: vscode.ChatResponseStream,
  model: vscode.LanguageModelChat,
  token: vscode.CancellationToken
): Promise<void> {
  stream.progress('Analyzing results...');
  
  const analyzePrompt =  `You are a QA engineer. Analyze the following pytest results and provide a brief summary:\n` +
      `- Which tests passed and which failed\n` +
      `- For failures, explain the likely root cause\n` +
      `- Suggest fixes for the code under test\n\n` +
      `**Generated test code:**\n\`\`\`python\n${generatedCode}\n\`\`\`\n\n` +
      `**Test output:**\n\`\`\`\n${testOutput}\n\`\`\``

  // Prompt the model with the latest test results and get an analysis
  const messages = [vscode.LanguageModelChatMessage.User(analyzePrompt)];
  const response = await model.sendRequest(messages, {}, token);

  // Show header once first token arrives so progress spinner stays visible
  let firstChunk = true;
  for await (const fragment of response.text) {
    if (firstChunk) {
      stream.markdown('\n**Analysis:**\n');
      firstChunk = false;
    }
    stream.markdown(fragment);
  }
}

export async function handleTestOption(request: vscode.ChatRequest, stream: vscode.ChatResponseStream, model: vscode.LanguageModelChat, token: vscode.CancellationToken): Promise<void> {
  // Initiate a new message array
  const messages = [vscode.LanguageModelChatMessage.User(TEST_PROMPT)];

  // Add all of the references the user passed into the context window
  messages.push(...await resolveReferences(request.references ?? []));

  // If there is a prompt we add that at the end, after the context is provided
  if (request.prompt) {
    messages.push(vscode.LanguageModelChatMessage.User(request.prompt));
  }

  // Notification to the user that we have started generating the tests
  stream.progress('Generating pytest tests...');

  // Send the messages to the model and start streaming the response
  const chatResponse = await model.sendRequest(messages, {}, token);

  // Stream the generated tests to the user as they arrive
  let generatedCode = '';
  let firstChunk = true;
  for await (const fragment of chatResponse.text) {
    if (firstChunk) {
      stream.markdown('**Generated tests:**\n```python\n');
      firstChunk = false;
    }
    generatedCode += fragment;
    stream.markdown(fragment);
  }
  stream.markdown('\n```\n\n');

  // Format the generated code for execution
  generatedCode = stripCodeFences(generatedCode);

  // Start setting up the test environment
  stream.progress('Setting up test environment...');

  // Try to setup the environment, streaming the error to the user if we encounter an issue
  try {
    // Create the test .venv file
    const { python, cleanup } = await createTestVenv();
    try {
      // Run the code generated by the model (create the pytest in here too)
      stream.progress('Running tests...');
      const result = await runPytest(python, generatedCode);
      
      // Take the stdout and stderr and create the test result response
      const output = (result.stdout + '\n' + result.stderr).trim();
      const passed = result.exitCode === 0;

      // Return the test results
      stream.markdown(`**Test results** (${passed ? 'PASSED' : 'FAILED'}):\n\`\`\`\n${output}\n\`\`\`\n`);

      // Ask the model to analyze the results
      await analyzeTestResults(generatedCode, output, stream, model, token);
    } finally {
      // Removes all of the temp code that was generated to run the tests
      await cleanup();
    }
  } catch (err: any) {
    // If an exception is raised we show that to the user
    stream.markdown(`**Execution error:**\n\`\`\`\n${err.message ?? err}\n\`\`\`\n`);
  }
  return;
}

export async function getPythonPath(): Promise<string> {
  try {
    // Fetch the users python extension to find out where the active .venv is
    const pyExtension = vscode.extensions.getExtension('ms-python.python');

    // Check for the .venv path through the native python extension works
    if (pyExtension) {
      // Activate the extension if its not on
      if (!pyExtension.isActive) { await pyExtension.activate(); }

      // Find the active env
      const details = pyExtension.exports?.settings?.getExecutionDetails?.(
        vscode.workspace.workspaceFolders?.[0]?.uri
      );

      // Return the path to the environment
      if (details?.execCommand?.[0]) { return details.execCommand[0]; }
    }
  } catch (e) {
    console.log('[jk-test] failed to get python path from ms-python:', e);
  }

  // Defacto base env that is associated with the users computer (we assume)
  return 'python3';
}

export function stripCodeFences(raw: string): string {
  return raw.trim().replace(/^```(?:python)?\s*\n?/, '').replace(/\n?```\s*$/, '').trim();
}

function execPromise(
  cmd: string,
  args: string[],
  opts: { timeout?: number } = {}
): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  // Runs a command in the environment and return the stdout, stderr, and exitCode
  return new Promise((resolve, reject) => {
    execFile(cmd, args, { timeout: opts.timeout }, (error, stdout, stderr) => {
      if (error && !('code' in error)) {
        reject(error);
        return;
      }

      resolve({
        stdout: stdout ?? '',
        stderr: stderr ?? '',
        exitCode: (error as any)?.code ?? 0,
      });
    });
  });
}

// creates a temp venv with pytest installed, returns the venv python path and a cleanup function
export async function createTestVenv(): Promise<{ python: string; cleanup: () => Promise<void> }> {
  // Create a virtual environment directory where we create the environment to run the pytests in
  const venvDir = path.join(os.tmpdir(), `jk_test_venv_${Date.now()}`);

  // Create the python environment
  const venvResult = await execPromise('python3', ['-m', 'venv', venvDir], { timeout: 30_000 });

  // Propagate to the user if an error condition occurs
  if (venvResult.exitCode !== 0) {
    throw new Error(`Failed to create venv: ${venvResult.stderr}`);
  }

  // Install pytest into the virtual environment
  const python = path.join(venvDir, 'bin', 'python');
  const installResult = await execPromise(python, ['-m', 'pip', 'install', 'pytest'], { timeout: 60_000 });

  if (installResult.exitCode !== 0) {
    throw new Error(`Failed to install pytest in venv: ${installResult.stderr}`);
  }

  // Return the python environment and the method to clean up the environment
  return {
    python,
    cleanup: async () => { await fs.rm(venvDir, { recursive: true, force: true }).catch(() => {}); },
  };
}

export async function runPytest(
  pythonPath: string,
  code: string,
  timeoutMs = 30_000
): Promise<{ stdout: string; stderr: string; exitCode: number }> {

  // Create a temporary file to hold the test code
  const tmpFile = path.join(os.tmpdir(), `jk_test_${Date.now()}.py`);
  await fs.writeFile(tmpFile, code, 'utf-8');

  // Execute the python code inside of the environment, cleaning up when its finished running
  try {
    return await execPromise(
      pythonPath,
      ['-m', 'pytest', tmpFile, '-v', '--tb=short', '--no-header'],
      { timeout: timeoutMs }
    );
  } finally {
    await fs.unlink(tmpFile).catch(() => {});
  }
}


async function readFileRef(val: any): Promise<string> {

  // Read the file reference and return the text to the model
  const uri = val instanceof vscode.Uri ? val : vscode.Uri.parse(val.toString());
  const doc = await vscode.workspace.openTextDocument(uri);

  return `File: ${uri.fsPath}\n\`\`\`\n${doc.getText()}\n\`\`\``;
}

async function readLocationRef(val: any): Promise<string> {
  // Read the location reference and return the text to the model (user provided)
  const uri = val.uri instanceof vscode.Uri ? val.uri : vscode.Uri.parse(val.uri.toString());
  const doc = await vscode.workspace.openTextDocument(uri);

  // If the user provides the range we read the characters
  if (val.range) {
    const range = new vscode.Range(
      val.range.start.line, val.range.start.character,
      val.range.end.line, val.range.end.character
    );

    // Return the user provided code
    return `Code from ${uri.fsPath}:\n\`\`\`\n${doc.getText(range)}\n\`\`\``;
  }

  // If we have no range we can just return the whole file
  return `File: ${uri.fsPath}\n\`\`\`\n${doc.getText()}\n\`\`\``;
}

export async function resolveReferences(
  refs: readonly vscode.ChatPromptReference[]
): Promise<vscode.LanguageModelChatMessage[]> {
  // Create a in memory reference of all the context references provided by the user
  const messages: vscode.LanguageModelChatMessage[] = [];

  for (const ref of refs) {
    const val = ref.value;
    try {
      let content: string | undefined;
      if (val instanceof vscode.Uri) {
        content = await readFileRef(val);
      } else if (val instanceof vscode.Location) {
        content = await readLocationRef(val);
      } else if (typeof val === 'object' && val !== null && 'uri' in val) {
        content = await readLocationRef(val);
      } else if (typeof val === 'object' && val !== null && 'scheme' in val) {
        content = await readFileRef(val);
      } else if (typeof val === 'string') {
        content = val;
      }

      // If its a parsable reference we add it to the new messages array
      if (content) {
        messages.push(vscode.LanguageModelChatMessage.User(content));
      }
    } catch (e) {
      console.log(`[jk-test] failed to read ref ${ref.id}:`, e);
    }
  }

  // Return all the parsed references to the model
  return messages;
}
